VinhNTHE171667/BE_ClinSkin

src/controllers/auth.controller.js, src/routes/users/auth.user-route.js
=> Dev-du reset password

src/controllers/auth.controller.js, src/middleware/auth.middleware.js, src/routes/users/auth.user-route.js
=> Dev du get Account

package-lock.json, package.json, src/controllers/category.controller.js, src/helpers/category.helper.js, src/models/category.model.js, src/routes/admins/category.admin-route.js, src/routes/admins/index.js, src/ultis/getRole.js
get all category, create category and delete category
=> Dev-du get all category, create category and delete category

src/controllers/category.controller.js, src/routes/admins/category.admin-route.js
api update category management
=> Dev du api update category management

src/controllers/brand.controller.js, src/models/brand.model.js, src/routes/admins/brand.admin-route.js
=> CRUD brand

src/routes/users/brand.user-route.js, src/routes/users/category.user-route.js, src/routes/users/index.js
create routes category and brand for user
=> Dev-du create routes category and brand for user

src/controllers/productController.js, src/controllers/promotionController.js, src/routes/admins/promotion.admin-route.js
Fix isActive, create promotion
=> Dev vinh- Fix isActive, create promotion

src/controllers/user.controller.js, src/routes/admins/index.js, src/routes/admins/user.admin-route.js
API get, active, inactive and delete user
=> Dev du API get, active, inactive and delete user

src/controllers/review.controller.js
=> Dev huy- fixManageReview

src/controllers/promotionController.js, src/middleware/validate.middleware.js
=> Dev vinh - Validator promotions

src/controllers/orderController.js, src/index.js, src/models/order.js, src/routes/staffs/index.js, src/routes/staffs/order.staff-route.js
=> Dev vinh - View and View Detail Order

docs/api/inventoryBatch.api.md, package-lock.json, package.json, src/controllers/brand.controller.js, src/controllers/inventoryBatch.controller.js, src/controllers/productController.js, src/controllers/productSalesHistory.controller.js, src/index.js, src/models/ProductSalesHistory.model.js, src/models/counter.model.js, src/models/inventoryBatch.model.js, src/models/product.js, src/models/promotion.js, src/routes/admins/index.js, src/routes/admins/inventoryBatch.routes.js, src/routes/admins/product.admin-route.js, src/routes/admins/sales-history.admin-route.js, src/services/inventoryBatch.service.js, src/ultis/cloudinary.js, src/validates/inventoryBatchValidator.js
- add srceen export order
- add screen manage batch
=> Dev ngoc anh

src/controllers/product-base.controller.js, src/routes/users/product.user-route.js
=> Dev du create api product detail

src/routes/users/product.user-route.js
=> SearchProductPage

src/controllers/product-base.controller.js, src/routes/users/product.user-route.js
=> Dev du api get all products

src/controllers/user.controller.js, src/models/user.model.js
Update model user and updateUser
=> Dev vinh - Update model user and updateUser

src/models/user.model.js
=> Dev du fix model user

src/controllers/product-base.controller.js, src/routes/users/product.user-route.js
=> Dev vinh - CategoryDetail

src/controllers/address.controller.js, src/models/address.model.js, src/routes/users/address.user-route.js, src/routes/users/index.js
=> Dev du feat: api crud address for user

src/controllers/admin.controller.js, src/models/admin.model.js, src/routes/admins/admin-account.admin-route.js
feat: api create account admin role
=> Dev du feat: api create account admin role

src/controllers/auth.controller.js
=> dev huy fixauthcontrollerupload

src/routes/review/review-route.js
=> Dev du refactor code

src/controllers/category.controller.js, src/controllers/inventoryBatch.controller.js
=> dev huy fixfeedbackreview

src/routes/review/review-route.js
=> Dev vinh - Fix review route

src/controllers/auth.controller.js
=> dev huy fixauthandpro

ORDER_STATUS_WORKFLOW.md, src/controllers/orderController.js, src/controllers/productSalesHistory.controller.js, src/index.js, src/models/order.js, src/routes/shipping/index.js, src/services/order.service.js
add api for shipper(demo)
- `pending` - Đang chờ xử lý
- `confirmed` - Đã xác nhận
- `picked_up` - Đã lấy hàng
- `in_transit` - Đang vận chuyển
- `carrier_confirmed` - Đơn vị vận chuyển đã xác nhận nhận hàng
- `failed_pickup` - Lấy hàng thất bại
- `delivery_pending` - Đang giao hàng
- `carrier_delivered` - Đơn vị vận chuyển đã giao hàng
- `delivery_failed` - Giao hàng thất bại
- `delivered_confirmed` - Khách hàng đã xác nhận nhận hàng
- `return` - Trả hàng
- `return_confirmed` - Đã xác nhận trả hàng
- `cancelled` - Đã hủy
- Từ `pending` → `cancelled` (có thể hủy đơn khi đang chờ)
- Từ `carrier_delivered` → `delivered_confirmed` (xác nhận đã nhận hàng)
- Từ `carrier_delivered` → `delivery_failed` (báo cáo giao hàng thất bại)
- Từ `pending` → `confirmed` hoặc `cancelled`
- Từ `confirmed` → …
=> Rework Order Status manager

src/controllers/orderController.js
=> Dev du fix currentstock stripe payment

src/services/inventoryBatch.service.js
fix add _id for getProductsWithNearExpiryBatches
=> Dev du fix add _id for getProductsWithNearExpiryBatches
